telegram:
  bot:
    token: ${BOT_TOKEN:xxx}
    username: ${BOT_USERNAME:BelVoiceMessagesBot}
    maxMessages: ${BOT_MAX_MESSAGES_IN_QUEUE:2}

decoder:
  location: ${DECODER_LOCATION:src/main/decoder}
  executor: ${DECODER_EXECUTOR:bin/bash}
  model: ${DECODER_MODEL:base}
  script: ${decoder.location}/${DECODE_SCRIPT_FILE:decode.sh}
  file: ${decoder.location}/${DECODER_FILE:decoder.py}
  bucket:
    location: ${BUCKET_LOCATION:${decoder.location}/voiceBucket}

logging:
  level:
    root: info
    by.bsu.voicemessages: info
